/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gastogasolina;

/**
 *
 * @author Jose Salvador
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kmRecorridos = new javax.swing.JTextField();
        tprecioGasolina = new javax.swing.JTextField();
        dineroGastado = new javax.swing.JTextField();
        tiempoUsado = new javax.swing.JTextField();
        gasolina100km = new javax.swing.JTextField();
        gasolina1km = new javax.swing.JTextField();
        kmhora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        msegundo = new javax.swing.JTextField();
        calcularConsumo = new javax.swing.JButton();
        calcularVelocidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TOTAL KM RECORRIDOS");

        jLabel2.setText("PRECIO GASOLINA/LITRO");

        jLabel3.setText("DINERO GASTADO EN GASOLINA");

        jLabel4.setText("TIEMPO TOTAL EN MINUTOS");

        gasolina100km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasolina100kmActionPerformed(evt);
            }
        });

        gasolina1km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasolina1kmActionPerformed(evt);
            }
        });

        jLabel5.setText("CONSUMO GASOLINA");

        jLabel6.setText("1 KM");

        jLabel7.setText("100 KM");

        jLabel8.setText("VELOCIDAD MEDIA");

        jLabel9.setText("km/h");

        jLabel10.setText("m/s");

        calcularConsumo.setText("Calcular consumo");
        calcularConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularConsumoActionPerformed(evt);
            }
        });

        calcularVelocidad.setText("Calcular Velocidad");
        calcularVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularVelocidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(calcularConsumo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(33, 33, 33)
                            .addComponent(gasolina100km))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(45, 45, 45)
                            .addComponent(gasolina1km, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(36, 36, 36)
                            .addComponent(msegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(kmhora, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calcularVelocidad)
                            .addComponent(dineroGastado)
                            .addComponent(tprecioGasolina)
                            .addComponent(kmRecorridos)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tiempoUsado))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(kmRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tprecioGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dineroGastado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tiempoUsado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gasolina1km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(kmhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gasolina100km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel10)
                        .addComponent(msegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularConsumo)
                    .addComponent(calcularVelocidad))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gasolina100kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasolina100kmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gasolina100kmActionPerformed

    private void gasolina1kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasolina1kmActionPerformed
        
    }//GEN-LAST:event_gasolina1kmActionPerformed

    private void calcularVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularVelocidadActionPerformed
        String tiempo, kmrecorridos, velkmdato, velmetrosdato;
        double tiempoMinutos;
        double kmrecorridosnumero, velkm, velmetros;
        //Recoger dato km recorridos
        kmrecorridos = kmRecorridos.getText();
        //Convertir dato a double
        kmrecorridosnumero = Double.valueOf(kmrecorridos);
        //Recogemos dato
        tiempo = tiempoUsado.getText();
        //Convertimos dato
        tiempoMinutos = Double.valueOf(tiempo);
        //Caluculamos la velocidad en segundos
        velkm = kmrecorridosnumero / (tiempoMinutos / 60);
        //Pasamos a dato de nuevo
        velkmdato = String.valueOf(velkm);
        //Mostramos en pantalla
        kmhora.setText(velkmdato);
        //Calculamos la velocidad en horas
        velmetros = (kmrecorridosnumero * 1000) / (tiempoMinutos * 60);
        //Pasamos a dato
        velmetrosdato = String.valueOf(velmetros);
        //Mostramos en pantalla
        msegundo.setText(velmetrosdato);  
    }//GEN-LAST:event_calcularVelocidadActionPerformed

    private void calcularConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularConsumoActionPerformed
        String litro1dato, litro100dato, kmrecorridos, gasolina, dinero, calculoporkm, calculopor100km;
        double litro1, litro100, litros, kmrecorridosnumero, precioGasolina, jdineroGastado;
        //Recoger dato km recorridos
        kmrecorridos = kmRecorridos.getText();
        //Convertir dato a double
        kmrecorridosnumero = Double.valueOf(kmrecorridos);
        //Recoger dato Precio de la Gasolina por litro
        gasolina = tprecioGasolina.getText();
        //Convertir dato a double
        precioGasolina = Double.valueOf(gasolina);
        //Recoger dato dinero gastado total
        dinero = dineroGastado.getText();
        //Convertir a numero
        jdineroGastado = Double.valueOf(dinero);
        //Calculamos el nº de litros
        litros =  jdineroGastado / precioGasolina;
        litro1 = litros / kmrecorridosnumero;
        //pasamos a dato
        litro1dato = String.valueOf(litro1);
        //Mostramos
        gasolina1km.setText(litro1dato);
        //Caluculamos los 100 km
        litro100 = litro1 * 100;
        //Pasamos a dato
        litro100dato = String.valueOf(litro100);
        //Mostramos
        gasolina100km.setText(litro100dato);
        
    }//GEN-LAST:event_calcularConsumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularConsumo;
    private javax.swing.JButton calcularVelocidad;
    private javax.swing.JTextField dineroGastado;
    private javax.swing.JTextField gasolina100km;
    private javax.swing.JTextField gasolina1km;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kmRecorridos;
    private javax.swing.JTextField kmhora;
    private javax.swing.JTextField msegundo;
    private javax.swing.JTextField tiempoUsado;
    private javax.swing.JTextField tprecioGasolina;
    // End of variables declaration//GEN-END:variables
}
